### ISSUE TITLE
Is "adm" instead of "dialout" the right group? Confusing when trying to install for Flora

### ISSUE THREAD

**Issue by stkdiretto** [adafruit/Trinket_Arduino_Linux#3]
Hey,

when following through the [getting started with FLORA guide,](https://learn.adafruit.com/getting-started-with-flora/download-software) one is directed to the [Linux Setup](https://learn.adafruit.com/adafruit-arduino-ide-setup/linux-setup) page and prompted to download the udev rules within this repository.

However, when plugging in a batch of recently bought FLORAs, the rule `ATTRS{idVendor}=="239a", MODE="0660", GROUP="adm"` is triggered, which will add `/dev/ttyACM*` to the `adm` group instead of `dialout`. Is this intentional? There was no way to add the non-privileged user accounts of our classroom setting to the `adm` group; rewriting said rule to `GROUP="dialout"` appears to have fixed the issue.

Did I overlook anything?

Addendum: The block was only added a few months ago in #1ac1f46 – maybe it flew under the radar until now?

**Comment by TheKitty** [comment]
I think you would get the fastest response posting in the Adafruit forums
which are continuously monitored

**Comment by ladyada** [comment]
we now use the board support package system
